name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pulumi pulumi-aws

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login

      - name: Pulumi stack select
        run: pulumi stack select dev

      - name: Pulumi refresh
        run: pulumi refresh --yes

      - name: Pulumi up
        run: pulumi up --yes

      - name: Save Pulumi outputs
        id: pulumi_outputs
        run: |
          MASTER_IP=$(pulumi stack output master_public_ip)
          WORKER1_IP=$(pulumi stack output worker1_public_ip)
          WORKER2_IP=$(pulumi stack output worker2_public_ip)
          PRIVATE_KEY=$(pulumi stack output private_key)

          echo "MASTER_IP=$MASTER_IP" >> $GITHUB_ENV
          echo "WORKER1_IP=$WORKER1_IP" >> $GITHUB_ENV
          echo "WORKER2_IP=$WORKER2_IP" >> $GITHUB_ENV
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Save SSH private key to GitHub secret
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Creating GitHub Secret for SSH private key"
          PUB_KEY=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/Konami33/actions/secrets/public-key | jq -r .key)
          KEY_ID=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/Konami33/actions/secrets/public-key | jq -r .key_id)
          ENCRYPTED_VALUE=$(echo -n "$PRIVATE_KEY" | openssl pkeyutl -encrypt -pubin -inkey <(echo "$PUB_KEY") | base64 -w 0)
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2024-06-29" \
            https://api.github.com/repos/Konami33/k3s-deploy-on-aws-withGithubAction/actions/secrets/SSH_PRIVATE_KEY \
            -d "{\"encrypted_value\":\"$ENCRYPTED_VALUE\",\"key_id\":\"$KEY_ID\"}"

