name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pulumi pulumi-aws

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login

      - name: Pulumi stack select
        run: pulumi stack select dev

      - name: Pulumi refresh
        run: pulumi refresh --yes

      - name: Pulumi up
        run: pulumi up --yes

      - name: Save Pulumi outputs
        id: pulumi_outputs
        run: |
          MASTER_IP=$(pulumi stack output master_public_ip)
          WORKER1_IP=$(pulumi stack output worker1_public_ip)
          WORKER2_IP=$(pulumi stack output worker2_public_ip)
          PRIVATE_KEY=$(pulumi stack output private_key)

          echo "MASTER_IP=$MASTER_IP" >> $GITHUB_ENV
          echo "WORKER1_IP=$WORKER1_IP" >> $GITHUB_ENV
          echo "WORKER2_IP=$WORKER2_IP" >> $GITHUB_ENV

          echo "$PRIVATE_KEY" > private_key.pem
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Save the SSH private key to GitHub secret
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Creating GitHub Secret for SSH private key"
          
          # Fetch the public key and key ID
          PUB_KEY_RESPONSE=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key)
          PUB_KEY=$(echo "$PUB_KEY_RESPONSE" | jq -r .key)
          KEY_ID=$(echo "$PUB_KEY_RESPONSE" | jq -r .key_id)
          
          # Encrypt the private key using the public key
          ENCRYPTED_VALUE=$(openssl rsautl -encrypt -pubin -inkey <(echo "$PUB_KEY") -in private_key.pem | base64 -w 0)
          
          # Create orr update the GitHub secret
          curl -X PUT \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/SSH_PRIVATE_KEY \
            -d "{\"encrypted_value\":\"$ENCRYPTED_VALUE\",\"key_id\":\"$KEY_ID\"}"
