name: Pulumi AWS Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-cli@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install pulumi pulumi-aws

    - name: Set up Pulumi
      run: |
        curl -fsSL https://get.pulumi.com | sh
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Pulumi up
      run: |
        pulumi stack select dev
        pulumi config set aws:region ap-southeast-1
        pulumi up --yes
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Save Pulumi outputs
      id: pulumi_outputs
      run: |
        echo "MASTER_IP=$(pulumi stack output master_public_ip)" >> $GITHUB_ENV
        echo "WORKER1_IP=$(pulumi stack output worker1_public_ip)" >> $GITHUB_ENV
        echo "WORKER2_IP=$(pulumi stack output worker2_public_ip)" >> $GITHUB_ENV
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
